title = "Shannon J. O'Leary"
baseURL = "https://example.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Molecular Ecology & Conservation Genomics, Department of Biology"
email = "soleary[at]anselm.edu"
favicon = " "
firstName = "The O'Lab"
lastName = "@ St. Anselm College"
phone = " "
profileImage = "img/portrait.jpg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = true
showPublications = true
showQr = false
showSkills = false

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
